name=input('你的名字是：')
print('好的',name,'我叫非凡的计算机')
bianqiang=int(input('你想要成为绝世高手吗？想的话扣1:'))
if bianqiang<2:
    print('那么跟着我的步奏走')
    ok=input('没有问题的话请回答OK:')
    print('欲练此功，必先自宫')
    有=input('请回答有没有自宫，没有的话不能继续操作了:')
    print('我知道你不会做的，所以就此别过了')
    继续=input('还想继续吗？那就请回答继续：')
    print('重头开始，试试扣1以外的数')
else:
    print('滚，马不停蹄的滚')
    是=input('等等，是不是我让你来这的？:')
    print('哦～刚刚忘记了')
    OK=input('来这次真的传授你绝世神功！同意的话点OK:')
    print('洗洗睡吧，大白天做什么梦呢！')
    print('感谢你的配合，其实我叫斯塔克是李客的助手。拜拜～')
    good=input('请回答对这个系统还满意吗？good/bad:')

